{{- $root := . -}}
{{- range $name, $value := .Values.tenant_groups }}
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: Project
metadata:
  name: {{ $value.name }}
  labels:
    demo.igniteme.dev/tenant-project: {{ $value.name }}
spec:
  providerConfigRef: 
    name: {{ $root.Values.providerConfigRef.name }}
  deletionPolicy: Delete
  forProvider:
    folderId: "182588266281"
    name: {{ $value.name }}-cloud-xpa
    projectId: {{ $value.name }}-cloud-xpa

---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
  name: {{ $value.name }}-owner
  labels:
    demo.igniteme.dev/tenant-owner: {{ $value.name }}
spec:
  providerConfigRef: 
    name: {{ $root.Values.providerConfigRef.name }}
  deletionPolicy: Delete
  forProvider:
    projectSelector:
      matchLabels:
        demo.igniteme.dev/tenant-project: {{ $value.name }}
    member: user:{{ $value.gmail }}
    role: roles/editor

{{- end }}
