---
apiVersion: v1
kind: Secret
metadata:
  name: gcp-resources-deploy-app
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:MavenWave-DevOps/gcp-resources-deploy-app
  sshPrivateKey: |
    cat ../secrets/id_rsa

