---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  name: platform-admin-crossplane
  annotations:
    crossplane.io/external-name: platform-admin-crossplane
spec:
  providerConfigRef:
    name: admin
  forProvider:
    description: Infra administrator
    displayName: Platform Admin

---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountIAMMember
metadata:
  name: platform-admin-crossplane
spec:
  providerConfigRef:
    name: admin
  forProvider:
    serviceAccountIdRef:
      name: platform-admin-crossplane
    role: "roles/iam.workloadIdentityUser"
    member: serviceAccount:test-app-384114.svc.id.goog[platform-admin/gcp-auth]

---
#Set up impersonate service account 
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountIAMMember
metadata:
  name: platform-admin-crossplane-impersonate
spec:
  providerConfigRef:
    name: admin
  forProvider:
    serviceAccountIdRef:
      name: platform-admin-crossplane
    role: "roles/iam.serviceAccountTokenCreator"
    member: serviceAccount:infra-tfe-sa@infra-tfe.iam.gserviceaccount.com

---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
  name: platform-admin-owner
  annotations:
    crossplane.io/external-name: platform-admin-editor
spec:
  deletionPolicy: Delete
  providerConfigRef:
    name: admin
  forProvider:
    project: test-app-384114
    member: serviceAccount:platform-admin-crossplane@test-app-384114.iam.gserviceaccount.com
    role: roles/owner
