---
apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: admin
spec:
  projectID: test-app-384114
  credentials:
    source: ImpersonateServiceAccount
    impersonateServiceAccount:
      name: platform-admin-crossplane@test-app-384114.iam.gserviceaccount.com
    # source: InjectedIdentity
      # name: 640263954415-compute@developer.gserviceaccount.com
