---
apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: platform-admin
spec:
  projectID: test-app-384114
  credentials:
    source: ImpersonateServiceAccount
    impersonateServiceAccount:
      name: platform-admin-crossplane@test-app-384114.iam.gserviceaccount.com
