---
apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: admin
spec:
  credentials:
    impersonateServiceAccount:
      name: 640263954415-compute@developer.gserviceaccount.com
      # name: platform-admin-crossplane@test-app-384114.iam.gserviceaccount.com
    source: ImpersonateServiceAccount
  projectID: test-app-384114
