---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: platform-admin-crossplane@test-app-384114.iam.gserviceaccount.com
  name: admin
  namespace: admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-role
subjects:
- kind: ServiceAccount
  name: admin
  namespace: admin
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
