apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

resources:
- service_account.yaml

helmCharts:
- name: external-dns
  releaseName: external-dns
  includeCRDs: true
  version: 1.11.0
  namespace: external-dns
  repo:  https://kubernetes-sigs.github.io/external-dns/
  valuesFile: values.yaml
