---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  name: external-dns
spec:
  deletionPolicy: Delete
  providerConfigRef:
    name: admin
  forProvider:
    displayName: Ignite 23 dev External DNS
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountIAMMember
metadata:
  name: external-dns
spec:
  providerConfigRef:
    name: admin
  forProvider:
    member: serviceAccount:test-app-384114.svc.id.goog[external-dns/external-dns]
    role: roles/iam.workloadIdentityUser
    serviceAccountIdRef:
      name: external-dns
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
  name: external-dns-dns-reader
spec:
  providerConfigRef:
    name: admin
  forProvider:
    member: serviceAccount:external-dns@test-app-384114.iam.gserviceaccount.com
    project: test-app-384114
    role: roles/dns.reader
---
apiVersion: dns.gcp.upbound.io/v1beta1
kind: ManagedZoneIAMMember
metadata:
  name: external-dns
spec:
  providerConfigRef:
    name: admin
  forProvider:
    member: serviceAccount:external-dns@test-app-384114.iam.gserviceaccount.com
    managedZone: igniteme-dev
    role: roles/dns.admin
