---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-deployment
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      serviceAccountName: backstage
      containers:
      - name: backstage
        command: ["node"]
        args:
        - "packages/backend"
        - "--config"
        - "app-config.yaml"
        image: us.gcr.io/test-app-384114/mayo-backstage:latest
        imagePullPolicy: Always
        ports:
        - name: backstage
          containerPort: 7007
        env:
        - name: ARGOCD_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: backstage-secrets
              key: ARGOCD_AUTH_TOKEN
        - name: AUTH_MICROSOFT_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: backstage-secrets
              key: AUTH_MICROSOFT_CLIENT_ID
        - name: AUTH_MICROSOFT_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: backstage-secrets
              key: AUTH_MICROSOFT_TENANT_ID
        - name: AUTH_MICROSOFT_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: backstage-secrets
              key: AUTH_MICROSOFT_CLIENT_SECRET 
        - name: AZURE_TOKEN
          valueFrom:
            secretKeyRef:
              name: backstage-secrets
              key: AZURE_TOKEN
        - name: BACKEND_SECRET
          valueFrom:
            secretKeyRef:
              name: backstage-secrets
              key: BACKEND_SECRET
        - name: GRAFANA_TOKEN 
          valueFrom:
            secretKeyRef:
              name: backstage-secrets
              key: GRAFANA_TOKEN
        - name: K8S_CLUSTER_NAME 
          valueFrom:
            secretKeyRef:
              name: backstage-secrets
              key: K8S_CLUSTER_NAME
        - name: K8S_SA_TOKEN
          valueFrom:
            secretKeyRef:
              name: backstage-secrets
              key: K8S_SA_TOKEN
        - name: K8S_URL 
          valueFrom:
            secretKeyRef:
              name: backstage-secrets
              key: K8S_URL
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: backstage-secrets
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backstage-secrets
              key: password
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: backstage-secrets
              key: database
        # - name: DB_USER
        #   valueFrom:
        #     secretKeyRef:
        #       name: backstage-secrets
        #       key: username
        # - name: DB_PASS
        #   valueFrom:
        #     secretKeyRef:
        #       name: pg-db-secret
        #       key: password
        # - name: DB_NAME
        #   valueFrom:
        #     secretKeyRef:
        #       name: pg-db-secret
        #       key: database

      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.28.0
        command:
          - "/cloud_sql_proxy"
          - "-ip_address_types=PRIVATE"
          - "-log_debug_stdout"
          - "-instances=test-app-384114:us-central1:backstage-dev=tcp:5432"
        securityContext:
          runAsNonRoot: true

