---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage
  annotations:
    iam.gke.io/gcp-service-account: platform-admin-crossplane@test-app-384114.iam.gserviceaccount.com

---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: backstage
spec:
  provider:
    gcpsm:
      projectID: test-app-384114
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterName: primary-cluster
          clusterProjectID: test-app-384114
          serviceAccountRef:
            name: backstage

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: backstage
  target:
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTH_MICROSOFT_CLIENT_ID: df395514-24ac-44a6-89f8-4b624f9d1c73
        AUTH_MICROSOFT_TENANT_ID: 542c5870-0684-4fe8-ac0a-44811fc2f43d
        AUTH_MICROSOFT_CLIENT_SECRET: '{{ .client_microsoft_secret }}'
        AZURE_TOKEN: '{{ .client_token }}'
        GRAFANA_TOKEN: '{{ .client_grafana_token }}'
        BACKEND_SECRET: '{{ .client_secret }}'
        ARGOCD_AUTH_TOKEN: '{{ .client_argocd_token }}'
        K8S_URL: https://127.0.0.1:49164
        K8S_CLUSTER_NAME: px-dev-cluster
        K8S_SA_TOKEN: fake
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: secret
        POSTGRES_HOST: localhost
        POSTGRES_PORT: '5432'
  data:
  - secretKey: client_secret
    remoteRef:
      key: backstage-backend-secret
  - secretKey: client_microsoft_secret
    remoteRef:
      key: backstage-microsoft-client-secret
  - secretKey: client_token
    remoteRef:
      key: backstage-azure-token
  - secretKey: client_grafana_token
    remoteRef:
      key: backstage-grafana-token
  - secretKey: client_argocd_token
    remoteRef:
      key: argocd-auth-token
