---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: Network
metadata:
  name: backstage-db-network
  labels:
    network.core.igniteme.dev/network-ref: backstage-db
spec:
  providerConfigRef:
    name: platform-admin
  forProvider:
    autoCreateSubnetworks: false
    routingMode: GLOBAL

---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: GlobalAddress
metadata:
  name: backstage-address
  labels:
    network.core.igniteme.dev/globalAddress-ref: backstage-db
spec:
  providerConfigRef:
    name: platform-admin
  forProvider:
    networkSelector:
      matchLabels:
        network.core.igniteme.dev/network-ref: backstage-db
    purpose: VPC_PEERING
    addressType: INTERNAL
    prefixLength: 16

# ---
# apiVersion: servicenetworking.gcp.upbound.io/v1beta1
# kind: Connection
# metadata:
#   name: backstage-connection
# spec:
#   providerConfigRef:
#     name: platform-admin
#   forProvider:
#     networkSelector:
#       matchLabels:
#         network.core.igniteme.dev/network-ref: backstage-db
#     reservedPeeringRangesSelector:
#       matchLabels:
#         network.core.igniteme.dev/globalAddress-ref: backstage-db
#     service: servicenetworking.googleapis.com

---
apiVersion: sql.gcp.upbound.io/v1beta1
kind: DatabaseInstance
metadata:
  name: backstage-database-instance
spec:
  deletionPolicy: Delete
  providerConfigRef:
    name: platform-admin
  forProvider:
    databaseVersion: POSTGRES_13
    deletionProtection: false
    region: us-central1
    settings:
      - tier: db-f1-micro
        diskType: PD_SSD
        ipConfiguration:
        - ipv4Enabled: false
          privateNetworkSelector: 
            matchLabels:
              network.core.igniteme.dev/network-ref: backstage-db
        locationPreference:
          - zone: us-central1-a
---
apiVersion: sql.gcp.upbound.io/v1beta1
kind: Database
metadata:
  name: backstage-database
spec:
  providerConfigRef:
    name: platform-admin
  forProvider:
    instanceRef:
      name: backstage-database-instance
---
apiVersion: sql.gcp.upbound.io/v1beta1
kind: User
metadata:
  name: postgres
spec:
  providerConfigRef:
    name: platform-admin
  forProvider:
    instanceRef:
      name: backstage-database-instance
    passwordSecretRef:
      key: password
      name: database-password
      namespace: crossplane-system
