---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: GlobalAddress
metadata:
  name: backstage-database
spec:
  providerConfigRef:
    name: platform-admin
  forProvider:
    network: projects/test-app-384114/global/networks/primary-network
    purpose: VPC_PEERING
    addressType: INTERNAL
    prefixLength: 16
  writeConnectionSecretToRef:
    name: postgres-connection-ref
    namespace: backstage
---
apiVersion: servicenetworking.gcp.upbound.io/v1beta1
kind: Connection
metadata:
  name: backstage-connect
spec:
  providerConfigRef:
    name: platform-admin
  forProvider:
    network: projects/test-app-384114/global/networks/primary-network
    parent: services/servicenetworking.googleapis.com
    reservedPeeringRanges: 
      - postgres
  writeConnectionSecretToRef:
    name: postgres-connection-ref
    namespace: backstage
---
apiVersion: sql.gcp.upbound.io/v1beta1
kind: DatabaseInstance
metadata:
  name: backstage-database-instance
spec:
  deletionPolicy: Delete
  providerConfigRef:
    name: platform-admin
  forProvider:
    databaseVersion: POSTGRES_11
    deletionProtection: false
    region: us-central1
    ipConfiguration:
      ipv4Enabled: true
      privateNetwork: projects/test-app-384114/global/networks/primary-network
    settings:
      - tier: db-f1-micro
        diskType: PD_SSD
---
apiVersion: sql.gcp.upbound.io/v1beta1
kind: Database
metadata:
  name: backstage-database
spec:
  providerConfigRef:
    name: platform-admin
  forProvider:
    instanceRef:
      name: backstage-database-instance
---
apiVersion: sql.gcp.upbound.io/v1beta1
kind: User
metadata:
  name: postgres
spec:
  providerConfigRef:
    name: platform-admin
  forProvider:
    instanceRef:
      name: backstage-database-instance
    passwordSecretRef:
      key: password
      name: database-password
      namespace: crossplane-system
