# ---
# apiVersion: compute.gcp.upbound.io/v1beta1
# kind: Network
# metadata:
#   name: backstage-database
#   labels:
#     network.core.projectx.dev/network-ref: database-demo
# spec:
#   providerConfigRef:
#     name: platform-admin
#   forProvider:
#     autoCreateSubnetworks: false
#     routingMode: GLOBAL
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: GlobalAddress
metadata:
  name: backstage-database
  labels:
    network.core.projectx.dev/globalAddress-ref: backstage-database
spec:
  providerConfigRef:
    name: platform-admin
  forProvider:
    networkRef:
      name: primary-network
    purpose: VPC_PEERING
    addressType: INTERNAL
    prefixLength: 16
---
apiVersion: sql.gcp.upbound.io/v1beta1
kind: DatabaseInstance
metadata:
  name: backstage-database-instance
  # annotations:
  #   meta.upbound.io/example-id: bigquery/v1beta1/connection
  #   uptest.upbound.io/pre-delete-hook: testhooks/delete-user.sh
  # labels:
  #   testing.upbound.io/example-name: instance
  # name: example-instance-${Rand.RFC1123Subdomain}
spec:
  deletionPolicy: Delete
  providerConfigRef:
    name: platform-admin
  forProvider:
    databaseVersion: POSTGRES_11
    deletionProtection: false
    region: us-central1
    settings:
      - tier: db-f1-micro
        diskType: PD_SSD
---
apiVersion: sql.gcp.upbound.io/v1beta1
kind: Database
metadata:
  # annotations:
  #   meta.upbound.io/example-id: bigquery/v1beta1/connection
  # labels:
  #   testing.upbound.io/example-name: db
  name: backstage-database
spec:
  providerConfigRef:
    name: platform-admin
  forProvider:
    instanceRef:
      name: backstage-database-instance
    # instanceSelector:
    #   matchLabels:
    #     testing.upbound.io/example-name: instance
---
apiVersion: sql.gcp.upbound.io/v1beta1
kind: User
metadata:
  # annotations:
  #   meta.upbound.io/example-id: sql/v1beta1/user
  # labels:
  #   testing.upbound.io/example-name: example_user
  name: postgres
spec:
  providerConfigRef:
    name: platform-admin
  forProvider:
    instanceRef:
      name: backstage-database-instance
    # instanceSelector:
    #   matchLabels:
    #     testing.upbound.io/example-name: example_instance
    passwordSecretRef:
      key: password
      name: database-password
      namespace: crossplane-system


