---
apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: Secret
metadata:
  name: backstage-microsoft-client-secret
spec:
  providerConfigRef:
    name: admin
  forProvider:
    replication:
    - automatic: true

---
apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: Secret
metadata:
  name: backstage-azure-token
spec:
  providerConfigRef:
    name: admin
  forProvider:
    replication:
    - automatic: true

---
apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: Secret
metadata:
  name: backstage-grafana-token
spec:
  providerConfigRef:
    name: admin
  forProvider:
    replication:
    - automatic: true

---
apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: Secret
metadata:
  name: backstage-backend-secret
spec:
  providerConfigRef:
    name: admin
  forProvider:
    replication:
    - automatic: true

---
apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: Secret
metadata:
  name: argocd-auth-token
spec:
  providerConfigRef:
    name: admin
  forProvider:
    replication:
    - automatic: true

---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  name: backstage
spec:
  providerConfigRef:
    name: admin
  forProvider:
    description: Backstage account for Workload Identity
    displayName: Backstage
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountIAMMember
metadata:
  name: backstage
spec:
  providerConfigRef:
    name: admin
  forProvider:
    member: serviceAccount:backstage@test-app-384114.svc.id.goog[backstage/backstage-secrets]
    role: roles/iam.workloadIdentityUser
    serviceAccountIdRef:
      name: backstage
---
apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: SecretIAMMember
metadata:
  name: backstage-microsoft
spec:
  providerConfigRef:
    name: admin
  forProvider:
    member: serviceAccount:backstage@test-app-384114.iam.gserviceaccount.com
    role: roles/secretmanager.secretAccessor
    secretIdRef:
      name: backstage-microsoft-client-secret
---
apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: SecretIAMMember
metadata:
  name: backstage-azure
spec:
  providerConfigRef:
    name: admin
  forProvider:
    member: serviceAccount:backstage@test-app-384114.iam.gserviceaccount.com
    role: roles/secretmanager.secretAccessor
    secretIdRef:
      name: backstage-azure-token
---
apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: SecretIAMMember
metadata:
  name: backstage-grafana
spec:
  providerConfigRef:
    name: admin
  forProvider:
    member: serviceAccount:backstage@test-app-384114.iam.gserviceaccount.com
    role: roles/secretmanager.secretAccessor
    secretIdRef:
      name: backstage-grafana-token

---
apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: SecretIAMMember
metadata:
  name: backstage-backend
spec:
  providerConfigRef:
    name: admin
  forProvider:
    member: serviceAccount:backstage@test-app-384114.iam.gserviceaccount.com
    role: roles/secretmanager.secretAccessor
    secretIdRef:
      name: backstage-backend-secret

---
apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: SecretIAMMember
metadata:
  name: backstage-argocd
spec:
  providerConfigRef:
    name: admin
  forProvider:
    member: serviceAccount:backstage@test-app-384114.iam.gserviceaccount.com
    role: roles/secretmanager.secretAccessor
    secretIdRef:
      name: argocd-auth-token
