apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crossplane-system

resources:
  - upbound-gcp-provider.yaml
  - pvc.yaml
# - gcp-provider.yaml

helmCharts:
- name: crossplane
  releaseName: crossplane
  includeCRDs: true
  version: 1.11.2
  namespace: crossplane-system
  repo: https://charts.crossplane.io/stable
  valuesFile: values.yaml

patches:
- path: add_deployment_fsgroup.yaml
