---
packageCache:
  medium: "crossplane"
  sizeLimit: 5Gi
  pvc: "crossplane"
resourcesCrossplane:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 250m
    memory: 512Mi
resourcesRBACManager:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 250m
    memory: 512Mi
