apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  labels:
    deployment: kustomization
    name: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: operators
  source:
    repoURL: https://github.com/fosterm-mw/ignite23.git
    path: gitops/backstage
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  
