apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  labels:
    deployment: kustomization
    name: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: operators
  source:
    repoURL: https://github.com/fosterm-mw/ignite23.git
    path: gitops/external-secrets
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: false
      selfHeal: true

