apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenants
  namespace: argocd
  labels:
    deployment: helm
    name: tenants
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: operators
  source:
    path: 'helm/tenant'
    repoURL: https://github.com/fosterm-mw/ignite23.git
    targetRevision: HEAD
    helm:
      releaseName: tenant
      valueFiles:
      - values.yaml
  # source:
  #   path: gitops/tenants
  destination:
    server: https://kubernetes.default.svc
    namespace: tenants
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    # syncOptions:
    # - CreateNamespace=true
