apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenants
  namespace: argocd
  labels:
    deployment: helm
    name: tenants
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: operators
  source:
    path: 'tenant'
    repoURL: https://github.com/fosterm-mw/ignite-tenants.git
    targetRevision: HEAD
    helm:
      releaseName: tenant
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tenants
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
