---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-secrets-sync
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - create
  - patch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-secrets-sync-rb
subjects:
- kind: ServiceAccount
  name: argocd-image-updater-secrets
roleRef:
  kind: Role
  name: argocd-secrets-sync
  apiGroup: ""
